from __future__ import annotations

from project.core import MODE_MULTI, ROUND_SINGLE

PAGE_TITLE_VOTE = "投票系統"
PAGE_TITLE_REPORT = "資料報告"

MODE_OPTIONS = [ROUND_SINGLE, MODE_MULTI]
PLACEHOLDER_NAME = "例如：小明"
PLACEHOLDER_CUSTOM_DRINK = "請輸入飲料名稱"
PLACEHOLDER_CUSTOM_ROUND = "例如：midterm"
SUCCESS_VOTE_ADDED_TEMPLATE = "已新增 {name} 的投票資料"

METRIC_TOTAL_VOTES = "總票數"
METRIC_VOTERS = "投票者"
EMPTY_LIST_PLACEHOLDER = "無"

TITLE_REPORT_PAGE = PAGE_TITLE_REPORT
CAPTION_REPORT_PAGE = "統計結果、圖表與輪次比較，提供快速分析與展示"

SIDEBAR_TITLE_MANAGEMENT = "### 投票管理"
SIDEBAR_CAPTION_DATA_PATH = "資料會寫入 `data/votes.csv`，送出後立即更新報表內容"
SIDEBAR_SUMMARY_TOTAL_TEMPLATE = "總票數：{total}"
SIDEBAR_SUMMARY_VOTERS_TEMPLATE = "投票者：{unique_voters}"
SIDEBAR_SUMMARY_ROUNDS_TEMPLATE = "輪次：{rounds_count}"
SIDEBAR_TITLE_CLEANUP = "### 資料清理"
SIDEBAR_CAPTION_CLEANUP = "刪除後的資料不可復原"
FORM_DELETE_ID = "delete_votes_form"
LABEL_DELETE_SELECTION = "選擇要刪除的資料"
PLACEHOLDER_DELETE_SELECTION = "可複選"
BUTTON_DELETE_SELECTED = "刪除選取資料"
WARNING_DELETE_NONE = "請先選擇要刪除的資料"
SUCCESS_DELETE_TEMPLATE = "已刪除 {count} 筆資料"

INFO_EMPTY_REPORT = "目前尚無投票資料，請先到「投票系統」頁面新增資料"
RECENT_VOTES_LIMIT = 8

COLUMN_ROUND = "輪次"
COLUMN_NAME = "姓名"
COLUMN_DRINK = "飲料"
COLUMN_VOTES = "票數"
COLUMN_RATIO = "占比"
COLUMN_MODES = "眾數"

SUMMARY_METRIC_MODES = "眾數"
SUMMARY_METRIC_LEAST = "最少票"
SUMMARY_TOOLTIP_MODES_TEMPLATE = "完整眾數品項：{modes}"
SUMMARY_TOOLTIP_LEAST_TEMPLATE = "完整最少票品項：{least}"
SUMMARY_COUNT_TEMPLATE = "{count} 票"

INFO_SINGLE_ROUND_ONLY = "目前只有單一輪次，新增多輪資料後會在這裡顯示比較結果"
CAPTION_CHANGES_PREFIX = "變化摘要："
CHANGES_JOINER = "；"

SUBHEADER_CHART_DISTRIBUTION = "投票分布圖"
CAPTION_CHART_DISTRIBUTION = "依票數高低排序，眾數會以較深色標示"
SUBHEADER_COUNT_SUMMARY = "票數摘要"
CAPTION_COUNT_SUMMARY = "各飲料票數與占比"
SUBHEADER_MULTI_ROUND_CHART = "多輪比較圖"
CAPTION_MULTI_ROUND_CHART = "以長條圖顯示各飲料在不同輪次的票數比較"
SUBHEADER_ROUND_COMPARISON = "輪次比較"
CAPTION_ROUND_COMPARISON = "多輪模式下快速比對每輪眾數"
SUBHEADER_DATA_DETAIL = "資料明細"
CAPTION_DATA_DETAIL = "完整投票紀錄"

FORM_VOTE_ID = "vote_form"
STATE_RESET = "reset_vote_form"
STATE_VOTE_MODE = "vote_mode"
STATE_VOTE_OPTION = "vote_option"
STATE_VOTE_ROUND_CHOICE = "vote_round_choice"
STATE_VOTE_NAME = "vote_name"
STATE_VOTE_CUSTOM_OPTION = "vote_custom_option"
STATE_VOTE_CUSTOM_ROUND_NAME = "vote_custom_round_name"
